export enum Role {
  All = 'All',
  StaffOfficer = 'Staff Officer',
  Director = 'Director',
  ShipStaff = 'Ship Staff',
  CO='CO',
  DNWNEEOfficeStaff='DNW&EE Office Staff',
  LOEO = 'LO/EO',
  SuperAdmin = 'Super Admin',
  MasterAdmin = 'Master Admin',
  EXO = 'EXO',
  DataEntry = 'Data Entry',
  ShipUser = 'Ship User',
  AreaCommander = 'Area Commander',
  DD = 'DD',
}
