export interface ShipInformation {
   shipInformationId: number,
   baseNameId: number,
   baseSchoolNameId: number,
   sqnId: number,
   operationalStatusId: number,
   shipTypeId: number,
   controlCode: string,
   callSign: string,
   nickName: string,
   class: string,
   fileUpload: string,
   displacementFullLoad: string,
   displacementLightWeight: string,
   manufacturer: string,
   dateOfCommission: Date,
   lengthLoa: string,
   lengthHom: string,
   breadthBmld: string,
   depth: string,
   draftFwd: string,
   draftAft: string,
   freshWaterCapacity: string,
   maximumSpeed: string,
   fualCapacity: string,
   maximumContinuousSpeed: string,
   luboilCapacity: string,
   cruisingSpeed: string,
   economicSpeed: string,
   address: string,
   authority: string,
   contactNo: string,
   status: number,
   menuPosition: number,
   isActive: boolean,
   remarks: string,
   authorityName:string,
   baseName:string,
   baseSchoolName:string,
   operationalStatus:string,
   shipType:string,
   sqnName:string,
   authorityId:string
   //fileUpload:string
}